from setuptools import find_packages, setup

setup(
    name="screenenv",
    version="0.0.1.dev0",
    description="A powerful Python library for creating and managing isolated desktop environments using Docker containers",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    license="MIT",
    author="ScreenEnv Contributors",
    keywords=["docker", "automation", "gui", "sandbox", "desktop", "playwright"],
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Software Development :: Testing",
        "Topic :: System :: Emulators",
        "Topic :: Desktop Environment",
    ],
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.10",
    install_requires=[
        "pydantic>=2.11.7",
        "psutil>=7.0.0",
        "docker>=7.1.0",
        "filelock>=3.18.0",
        "playwright>=1.52.0",
        "fastapi>=0.115.13",
        "requests>=2.32.4",
        "uvicorn>=0.15.0",
        "mcp>=1.9.4",
        # for demo
        "smolagents==1.15.0",
        "huggingface_hub==0.33.1",
        "openai==1.91.0",
        "gradio-modal==0.0.4",
    ],
    extras_require={
        "dev": [
            "pytest>=7.0.0",
            "pytest-asyncio>=0.21.0",
            "pytest-cov>=4.0.0",
            "black>=23.0.0",
            "isort>=5.12.0",
            "flake8>=6.0.0",
            "mypy>=1.0.0",
            "pre-commit>=3.0.0",
        ],
        "test": [
            "pytest>=7.0.0",
            "pytest-asyncio>=0.21.0",
            "pytest-cov>=4.0.0",
        ],
    },
    project_urls={
        "Homepage": "https://github.com/huggingface/screenenv",
        "Repository": "https://github.com/huggingface/screenenv",
        "Documentation": "https://github.com/huggingface/screenenv#readme",
        "Issues": "https://github.com/huggingface/screenenv/issues",
    },
    include_package_data=True,
)
